#!/usr/bin/env bash
# For the 9th iteration, displays Best School
#+ and then Hi on a new line.
#+ Must use while loop and if statmt
# For and until forbidden

i=1
while [ $i -le 10 ]
do
    echo Best School
    if [ $i -eq 9 ]
    then 
        echo Hi
    fi
    ((i++))
done