#!/usr/bin/env bash
# Display the clock for 12hr 59 mins

hour=0
while [ $hour -le 12 ]
do
    echo Hour: $hour
    minute=1
    while [ $minute -le 59 ]
    do
        echo $minute
        ((minute++))
    done
    ((hour++))
done