#!/usr/bin/env bash
# Displays the content of the current directory in list format
# Only displays the part of the name after the first dash

files=$(ls)
for file in $files
do
    echo "$file" | cut -d '-' -f2
done