#!/usr/bin/env bash
# Write a Bash script that creates an RSA key pair.
# Requirements:
# 	Name of the created private key must be school
# 	Number of bits in the created key to be created 4096
# 	The created key must be protected by the passphrase betty

# Set the name of the private key
private_key="school"

# Set the number of bits for the key
bits=4096

# Set the passphrase for the key
passphrase="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b $bits -f "$private_key" -P "$passphrase"
